##===- tools/clang-check/Makefile --------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
#LLVM_SRC_ROOT = /home/xiaohe/FYP/LLVM/llvm
#LLVM_OBJ_ROOT = /home/xiaohe/FYP/LLVM/build

CLANG_LEVEL := ../..

DIRS = tools
EXTRA_DIST = include


# Set this variable to the top of the LLVM source tree.
LLVM_SRC_ROOT = /home/xiaohe/FYP/LLVM/llvm

# Set this variable to the top level directory where LLVM was built
# (this is *not* the same as OBJ_ROOT as defined in LLVM's Makefile.config).
LLVM_OBJ_ROOT = /home/xiaohe/FYP/LLVM/build

# Set the directory root of this project's source files
PROJ_SRC_ROOT := $(subst //,/,/home/xiaohe/FYP/LLVM/llvm/tools/clang/tools/SessionTypeExtractor)

# Set the root directory of this project's object files
PROJ_OBJ_ROOT := $(subst //,/,/home/xiaohe/FYP/LLVM/llvm/tools/clang/tools/SessionTypeExtractor)

# Set the root directory of this project's install prefix
PROJ_INSTALL_ROOT := /home/xiaohe/FYP/LLVM/llvm/tools/clang/tools/SessionTypeExtractor/EXE




include $(CLANG_LEVEL)/Makefile
