##===- projects/sample/tools/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
CLANG_LEVEL := ../../..

#
# List all of the subdirectories that we will compile.
#
DIRS=SessionTypeExtractor

include $(CLANG_LEVEL)/Makefile
